version: '2'
services:
  mongoConfig1:
    container_name: mongoConfig1
    image: mongo:latest
    command: mongod -f /mongodb/config/replConf1.config
    environment:
      TERM: xterm
    volumes:
      - ./mongodb:/mongodb
      - ./scripts:/scripts

  mongoConfig2:
    container_name: mongoConfig2
    image: mongo:latest
    command: mongod -f /mongodb/config/replConf2.config
    environment:
      TERM: xterm
    volumes:
      - ./mongodb:/mongodb
      - ./scripts:/scripts

  mongoShard1:
    container_name: mongoShard1
    image: mongo:latest
    command: mongod -f /mongodb/config/shardConf1.config
    environment:
      TERM: xterm
    volumes:
      - ./mongodb:/mongodb
      - ./scripts:/scripts

  mongoShard2:
    container_name: mongoShard2
    image: mongo:latest
    command: mongod -f /mongodb/config/shardConf2.config
    environment:
      TERM: xterm
    volumes:
      - ./mongodb:/mongodb
      - ./scripts:/scripts

  mongoShard3:
    container_name: mongoShard3
    image: mongo:latest
    command: mongod -f /mongodb/config/shardConf3.config
    environment:
      TERM: xterm
    volumes:
      - ./mongodb:/mongodb
      - ./scripts:/scripts

  router:
    container_name: router 
    image: mongo:latest
    command: mongos -f /mongodb/config/router.config
    volumes:
      - ./mongodb:/mongodb
      - ./scripts:/scripts
    environment:
      TERM: xterm
    depends_on:
      - mongoConfig1
      - mongoConfig2
