version: '2'
services:
  mongorepl1:
    container_name: mongorepl1
    image: mongo:latest
    command: mongod --replSet replServer --dbpath /data/db --port 27017 --bind_ip_all
    environment:
      TERM: xterm
    ports:
      - 27017:27017
    volumes:
      - ./scripts:/scripts
  mongorepl2:
    container_name: mongorepl2
    image: mongo:latest
    command: mongod --replSet replServer --dbpath /data/db --port 27018 --bind_ip_all
    environment:
      TERM: xterm
    ports:
      - 27018:27018
    volumes:
      - ./scripts:/scripts
  mongorepl3:
    container_name: mongorepl3
    image: mongo:latest
    command: mongod --replSet replServer --dbpath /data/db --port 27019 --bind_ip_all
    environment:
      TERM: xterm
    ports:
      - 27019:27019
    volumes:
      - ./scripts:/scripts
    
